TRAIT_NODES = {
    "kindness": "Tendency to be caring and considerate toward others",
    "aggressiveness": "Tendency toward hostility and confrontation",
    "rationality": "Tendency to think logically rather than emotionally",
    "emotional_stability": "Ability to remain calm and steady under pressure",
    "honesty": "Tendency to be truthful and transparent",
    "optimism": "Tendency to expect positive outcomes",
    "empathy": "Ability to understand and share others' feelings",
    "curiosity": "Desire to learn and explore new things",
    "calmness": "Tendency to remain tranquil and composed",
    "carefulness": "Tendency to be cautious and attentive to detail",
    "anxiety": "Tendency to worry and feel uneasy",
}

PRIMARY_EMOTIONS = {
    "happiness": "Feeling of joy and contentment",
    "sadness": "Feeling of sorrow and unhappiness",
    "fear": "Unpleasant emotion caused by perceived threat",
    "disgust": "Strong feeling of dislike or revulsion",
    "anger": "Strong feeling of annoyance or displeasure",
    "surprise": "Feeling of astonishment from something unexpected",
}

SUB_EMOTIONS = [
    ("admiration",             "surprise",  "Respect for someone"),
    ("adoration",              "happiness", "Deep love and admiration"),
    ("aesthetic_appreciation", "happiness", "Appreciation of beauty"),
    ("amusement",              "happiness", "Finding something funny"),
    ("awe",                    "surprise",  "Wonder or admiration"),
    ("awkwardness",            "disgust",   "Social discomfort"),
    ("boredom",                "disgust",   "Lack of interest"),
    ("calmness",               "happiness", "Tranquility"),
    ("confusion",              "surprise",  "Lack of understanding"),
    ("craving",                "happiness", "Strong desire"),
    ("empathic_pain",          "sadness",   "Feeling others' suffering"),
    ("entrancement",           "surprise",  "Being mesmerized"),
    ("excitement",             "happiness", "Great enthusiasm"),
    ("horror",                 "fear",      "Intense fear or shock"),
    ("interest",               "surprise",  "Curiosity or concern"),
    ("joy",                    "happiness", "Great pleasure"),
    ("nostalgia",              "sadness",   "Sentimental longing"),
    ("relief",                 "happiness", "Alleviation of distress"),
    ("romance",                "happiness", "Romantic love"),
    ("satisfaction",           "happiness", "Fulfillment"),
    ("sexual_desire",          "happiness", "Physical longing"),
    ("anxiety",                "fear",      "Worry or unease"),
]
