TRAIT_NODES = {
    "kindness": "Tendency to be caring and considerate toward others",
    "aggressiveness": "Tendency toward hostility and confrontation",
    "rationality": "Tendency to think logically rather than emotionally",
    "emotional_stability": "Ability to remain calm and steady under pressure",
    "honesty": "Tendency to be truthful and transparent",
    "optimism": "Tendency to expect positive outcomes",
    "empathy": "Ability to understand and share others' feelings",
    "curiosity": "Desire to learn and explore new things",
    "calmness": "Tendency to remain tranquil and composed",
    "carefulness": "Tendency to be cautious and attentive to detail",
    "anxiety": "Tendency to worry and feel uneasy",
}

EMOTIONS = [
    ("admiration",              "Respect for someone"),
    ("adoration",               "Deep love and admiration"),
    ("aesthetic_appreciation",  "Appreciation of beauty"),
    ("amusement",               "Finding something funny"),
    ("awe",                     "Wonder or admiration"),
    ("awkwardness",             "Social discomfort"),
    ("boredom",                 "Lack of interest"),
    ("calmness",                "Tranquility"),
    ("confusion",               "Lack of understanding"),
    ("craving",                 "Strong desire"),
    ("empathic_pain",           "Feeling others' suffering"),
    ("entrancement",            "Being mesmerized"),
    ("excitement",              "Great enthusiasm"),
    ("horror",                  "Intense fear or shock"),
    ("interest",                "Curiosity or concern"),
    ("joy",                     "Great pleasure"),
    ("nostalgia",               "Sentimental longing"),
    ("relief",                  "Alleviation of distress"),
    ("romance",                 "Romantic love"),
    ("satisfaction",            "Fulfillment"),
    ("sexual_desire",           "Physical longing"),
    ("anxiety",                 "Worry or unease"),
]
